name: Feature Request
description: Use this template to request new features
labels: ["enhancement"]
title: "[Feature Request]: "

# Form fields:
fields:
  - type: textarea
    id: description
    attributes:
      label: Describe the Feature
      description: Please provide a detailed description of the feature you want to request.
    validations:
      required: true
